name: 'SBOM Generation and Scanning'
description: 'This action generates a Software Bill of Materials (SBOM) for the project and scans it for vulnerabilities.'
author: 'voolyvex@'
outputs:
  sbom-file:
    description: 'The syftgenerated SBOM file.'
    value: ${{ steps.generate-sbom.outputs.sbom-file }}
runs:
  using: 'docker'
  image: 'Dockerfile'
