name: Build-Tag-Push
on: 
  workflow_dispatch
permissions: {}
jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd 
      - name: docker_build_tag_push
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          STATE_KEY: ${{ secrets.STATE_KEY }}
        run: |
          docker build -t application-final .
          docker tag application-final acr$STATE_KEYacmp2400.azurecr.io/final
          docker login acr$STATE_KEYacmp2400.azurecr.io --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET
          docker push acr$STATE_KEYacmp2400.azurecr.io/final
