name: Build-Curl
on:
  workflow_dispatch

permissions: read-all
jobs:
  Build-and-curl:
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd 
      - name: docker_build
        run: |
          docker build -t pipeline-test .
      - name: docker_run
        env:
          # Pull from gh Secrets into the runner's shell env
          DJANGO_SECRET_KEY: ${{ vars.DJANGO_SECRET_KEY }}
        run: |
          # Run migrations first, then start the django server
          # docker run --rm pipeline-test python manage.py migrate
          docker run -d --name curl-app -p 8000:8000 -e DJANGO_SECRET_KEY="$DJANGO_SECRET_KEY" -e DEBUG="True" -e ALLOWED_HOSTS="*" pipeline-test
          sleep 7
          echo "--- Container Environment ---"
          docker exec curl-app env | grep DJANGO
      - name:  curl_ftw
        run: |
          curl -f http://localhost:8000/
      - name: docker_logs
        if: always()
        run: docker logs curl-app
