name: SBOM-Scan
on:
  workflow_dispatch
permissions: {}
jobs:  
  sbom-scan:
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd 
      - name: sbom_gen_and_scan
        uses: ./.github/actions/sbom-scan 
        with:
          name: project-sbom
          path: snom.json
          compression-level: 0
      