name: Terra-Test
on: 
  workflow_dispatch
permissions: {}
jobs:
  Terraform-stage-1:
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd 
      - name: terraform-stage-1
        uses: ./.github/actions/terraform 
        with:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          STATE_KEY: 'jknapp'
          TF_STAGE: 'stage1'
